#!/bin/sh

# workspace-right
# by slackhead/dive
# REQUIRES: wmctrl

CURWS=$(wmctrl -d | grep "*" | cut -d' ' -f1)
TOTAL=$(($(wmctrl -d | wc -l)-1))
NEWWS=$(($CURWS+1))

[ $NEWWS -gt $TOTAL ] && NEWWS=0
wmctrl -s $NEWWS
