#!/bin/sh

# workspace-left
# by slackhead/dive
# REQUIRES: wmctrl

CURWS=$(wmctrl -d | grep "*" | cut -d' ' -f1)
TOTAL=$(($(wmctrl -d | wc -l)-1))
NEWWS=$(($CURWS-1))

[ $NEWWS -lt 0 ] && NEWWS=$TOTAL
wmctrl -s $NEWWS
