#!/bin/sh

# REQUIRES: xdotool
# Decrease _NET_WM_WINDOW_OPACITY
# Max = 4294967294

set -e

OPFILE=~/.xopacity
FWIN=$(xdotool getwindowname $(xdotool getwindowfocus))
WINID=$(xwininfo -root -tree | grep "$FWIN" | awk '{print $1}')
INC=42949672
CURV=$(xprop -id $WINID | grep _NET_WM_WINDOW_OPACITY | cut -d' ' -f3)

[ -z "$CURV" ] && CURV=4294967294
let NEWV=$(($CURV-$INC))
[ $NEWV -lt 0 ] && NEWV=0

xprop -id $WINID -f _NET_WM_WINDOW_OPACITY 32c -set _NET_WM_WINDOW_OPACITY $NEWV
class=$(xprop -id $WINID | grep WM_CLASS | cut -d'"' -f4)

[ -r $OPFILE ]&&[ -n "$(grep -ie "^$class=" $OPFILE)" ] \
    && sed -i "s/$class=.*/$class=$NEWV/" $OPFILE \
    || echo "$class=$NEWV" >> $OPFILE

# vim: tw=0
