#!/bin/sh

# REQUIRES: xdotool
# Set full opacity

OPFILE=~/.xopacity
FWIN=$(xdotool getwindowname $(xdotool getwindowfocus))
WINID=$(xwininfo -root -tree | grep "$FWIN" | head -n 1 | awk '{print $1}')

xprop -id $WINID -f _NET_WM_WINDOW_OPACITY 32c -set _NET_WM_WINDOW_OPACITY 4294967294
class=$(xprop -id $WINID | grep WM_CLASS | cut -d'"' -f4)

[ -r $OPFILE ] && \
    L=$(grep -ne "^$class=" $OPFILE) && sed -i "${L%:*} d" $OPFILE

# vim: tw=0
